FROM ubuntu:18.04 AS builder

ENV NGINX_PATH /etc/nginx
ENV NGINX_VERSION 1.20.0

WORKDIR /opt

RUN apt-get update && \
    apt-get install -y curl git libpcre3 libpcre3-dev zlib1g zlib1g-dev build-essential cmake wget libssl-dev;

RUN curl -O https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz && \
    wget -O stream.mp4 https://www.dprojects.it/thesis/BBB-short.mp4 && \
    tar xvzf nginx-$NGINX_VERSION.tar.gz && \
    git clone https://github.com/arut/nginx-rtmp-module.git && \
    cd nginx-$NGINX_VERSION && \
    ./configure                                 \
    --prefix=/etc/nginx                    \
    --sbin-path=/usr/sbin/nginx \
    --modules-path=/usr/lib/nginx/modules \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --pid-path=/var/run/nginx.pid \
    --add-module=../nginx-rtmp-module       \
    --lock-path=/var/run/nginx.lock \
    --http-client-body-temp-path=/var/cache/nginx/client_temp \
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
    --user=nginx \
    --group=nginx \
    --with-http_ssl_module                  \
    --with-http_v2_module && \
    make && \
    make install;


FROM ubuntu:18.04

COPY --from=builder /usr/sbin/nginx /usr/sbin/
COPY --from=builder /etc/nginx/ /etc/nginx/
COPY --from=builder /opt/stream.mp4 /root/stream.mp4

RUN groupadd  nginx \
    && useradd -m -d  /var/cache/nginx -s /sbin/nologin -g nginx nginx \
    && mkdir -p /var/log/nginx \
    && touch /var/log/nginx/access.log /var/log/nginx/error.log \
    && chown nginx: /var/log/nginx/access.log /var/log/nginx/error.log \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log \
    && apt-get update \
    && apt-get install -y ffmpeg build-essential zlib1g zlib1g-dev libssl-dev

EXPOSE 8080

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]